name:                aac
version:             0.1.0.0
github:              "githubuser/aac"
license:             BSD3
author:              "Emily Sillars"
maintainer:          "ems2331@columbia.edu"
copyright:           "2021 Emily Sillars"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aac#readme>

dependencies:
- repa
- JuicyPixels
- JuicyPixels-repa
- bytestring
- text
- split
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  aac-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - repa
    - JuicyPixels
    - JuicyPixels-repa
    - bytestring
    - text
    - split
    - aac
    - directory
    

tests:
  aac-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aac
